-- User registration & login geo tracking
CREATE TABLE IF NOT EXISTS user_geo_log (
  id          VARCHAR(36)  PRIMARY KEY,
  userId      VARCHAR(36)  NOT NULL,
  eventType   VARCHAR(20)  NOT NULL,
  ip          VARCHAR(64)  DEFAULT NULL,
  country     VARCHAR(100) DEFAULT NULL,
  city        VARCHAR(100) DEFAULT NULL,
  region      VARCHAR(100) DEFAULT NULL,
  latitude    DECIMAL(10,7) DEFAULT NULL,
  longitude   DECIMAL(10,7) DEFAULT NULL,
  geoSource   VARCHAR(10)  DEFAULT 'IP',
  device      VARCHAR(50)  DEFAULT NULL,
  browser     VARCHAR(100) DEFAULT NULL,
  os          VARCHAR(100) DEFAULT NULL,
  platform    VARCHAR(50)  DEFAULT NULL,
  userAgent   TEXT         DEFAULT NULL,
  createdAt   DATETIME     DEFAULT NOW(),
  INDEX idx_userId (userId),
  INDEX idx_eventType (eventType),
  INDEX idx_createdAt (createdAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `user`
  ADD COLUMN IF NOT EXISTS registrationIp VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS registrationCountry VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS registrationCity VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS registrationLat DECIMAL(10,7) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS registrationLon DECIMAL(10,7) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lastLoginIp VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lastLoginCountry VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lastLoginCity VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lastLoginLat DECIMAL(10,7) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lastLoginLon DECIMAL(10,7) DEFAULT NULL;

ALTER TABLE pending_registration
  ADD COLUMN IF NOT EXISTS registrationIp VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS registrationCountry VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS registrationCity VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS registrationLat DECIMAL(10,7) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS registrationLon DECIMAL(10,7) DEFAULT NULL;
