/** Default subscription plans — used by admin seed & fresh installs */
export const DEFAULT_PLANS = [
  {
    plan: 'FREE',
    displayName: 'Free',
    price: 0,
    currency: 'INR',
    durationDays: 0,
    description: 'Basic access with limited interests',
    isActive: true,
    permissions: {
      canChat: false,
      interestLimit: 5,
      canSeeContact: false,
      canBoostProfile: false,
      canSeeWhoViewed: false,
      unlimitedInterests: false,
      aiMatchScore: false,
      kundaliMatchPdf: false,
    },
  },
  {
    plan: 'SILVER',
    displayName: 'Silver',
    price: 749,
    currency: 'INR',
    durationDays: 30,
    description: 'See contacts and who viewed your profile',
    isActive: true,
    permissions: {
      canChat: false,
      interestLimit: 50,
      canSeeContact: true,
      canBoostProfile: false,
      canSeeWhoViewed: true,
      unlimitedInterests: false,
      aiMatchScore: false,
      kundaliMatchPdf: false,
    },
  },
  {
    plan: 'GOLD',
    displayName: 'Gold',
    price: 1499,
    currency: 'INR',
    durationDays: 30,
    description: 'Chat, unlimited interests, profile boost',
    isActive: true,
    permissions: {
      canChat: true,
      interestLimit: -1,
      canSeeContact: true,
      canBoostProfile: true,
      canSeeWhoViewed: true,
      unlimitedInterests: true,
      aiMatchScore: false,
      kundaliMatchPdf: false,
    },
  },
  {
    plan: 'PLATINUM',
    displayName: 'Platinum',
    price: 2999,
    currency: 'INR',
    durationDays: 30,
    description: 'All Gold features plus AI match score & Kundali PDF',
    isActive: true,
    permissions: {
      canChat: true,
      interestLimit: -1,
      canSeeContact: true,
      canBoostProfile: true,
      canSeeWhoViewed: true,
      unlimitedInterests: true,
      aiMatchScore: true,
      kundaliMatchPdf: true,
    },
  },
  {
    plan: 'EARLY_BIRD',
    displayName: 'Early Bird (Free Full Access)',
    price: 0,
    currency: 'INR',
    durationDays: 365,
    description: 'Auto-assigned to first N registered users — full premium features free',
    isActive: true,
    permissions: {
      canChat: true,
      interestLimit: -1,
      canSeeContact: true,
      canBoostProfile: true,
      canSeeWhoViewed: true,
      unlimitedInterests: true,
      aiMatchScore: true,
      kundaliMatchPdf: true,
    },
  },
];

export const DEFAULT_EARLY_BIRD_SETTINGS = {
  enabled: true,
  limit: 1000,
  claimed: 0,
  planId: 'GOLD',
  durationUnit: 'years',
  durationValue: 1,
  durationDays: 365,
  autoAssignOnSignup: false,
  title: 'Early Bird Offer — Free Full Access',
  subtitle: 'First registered members get premium features free. Limited slots!',
};
